### ISSUE TITLE
"cannot call method 'call' of undefined"

### ISSUE THREAD

**Issue by Gloryofthe80s** [Muon/node-etsy#1]
I just installed node-etsy (thanks for making it!), and can't seem to get it to make a successful fetch. 

I'm just using the default example for the query.

Here's the error and my code:
https://gist.github.com/Gloryofthe80s/62c85f2aa32a69eb35f7

**Comment by Muon** [comment]
This was written _ages_ ago. As best as I can tell, it's using the old HTTP interface and that's why it's crapping out. Those bits should be rewritten using [`http.request()`](http://nodejs.org/api/http.html#http_http_request_options_callback).

**Comment by Gloryofthe80s** [comment]
Yeah, definitely. I saw that this is 3 years old after I posted. Thanks for the response; sorry for not looking closer!
